### ISSUE TITLE
because the public key is not available

### ISSUE THREAD

**Issue by WChengLei** [termux/game-packages-21-bin#1]
After I set the sources to this, when i exec `pkg up` ,  There have a error `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B`

How shuld I do? 

![2022-11-30 16-43-06](https://user-images.githubusercontent.com/9523436/204749041-60ddffed-4f8d-499d-990f-8e26fd81cb87.png)

**Comment by Grimler91** [comment]
Download latest [termux-keyring](https://packages.termux.dev/termux-main-21/pool/main/t/termux-keyring/termux-keyring_1.5_all.deb), install with `dpkg -i /path/to/termux-kerying_1.5_all.deb`.

**Comment by WChengLei** [comment]
It's worked!!! Thank you very much!!!
